### ISSUE TITLE
Embrace the git, bathe in it

### ISSUE THREAD

**Issue by j4qfrost** [maadeagbo/VulkanDemoScene#12]
It looks like you're integrating libraries directly into the project instead of leveraging submodules. I would fork something like imgui and make modifications there then integrate it as a submodule. The upside is that if there's a new feature that's released upstream, you can more agilely make the change to add it to your main project. Less copypasta. This may also be useful if you want to reuse libraries in other projects. Though there may be a trade off with book keep the separate forks.

**Comment by maadeagbo** [comment]
Thanks for the advice :) I used submodules heavily before but found the back and forth to be too much busy work. Also, it was too easy to make edits to a file that I forgot to sync to the submodule's root repo. That's why I moved to my current workflow.

Maybe I'll go back to it one day.
